name: zidanfath_getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.1
  get: 4.6.5
  flex_color_scheme: 6.1.1
  google_fonts: 3.0.1
  easy_splash_screen: 1.0.4
  font_awesome_flutter: 10.2.1
  fluttertoast: 8.1.1
  getwidget: 3.0.1
  url_launcher: 6.1.7
  easy_refresh: 3.0.4+4
  card_loading: 0.2.2
  http: 0.13.5
  permission_handler: 10.2.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

